### ISSUE TITLE
[TODO]  package maintenence

### ISSUE THREAD

**Issue by aissat** [aissat/easy_localization_loader#19]
- [ ]  work on unit testing 
- [ ] Add code coverage information and badges
- [x] add ci for testing before merges #54 by @bw-flagship 
- [ ] add code doc
